[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    olkal/HX711_ADC
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    bblanchon/ArduinoJson@^7
    paulstoffregen/OneWire
    milesburton/DallasTemperature

build_flags =
    -DCORE_DEBUG_LEVEL=3
